export interface generalProps{
  tittle?: string,
  color?: string,
  children?: React.ReactNode,
  cardW?: string,
  cardH?: string,
  cardBG?: string,
  spanColor?: string,
  spanUB?: string,
  spanRL?: string,
  spanW?: string,
  spanH?: string,
  position?: string,
  topOrBottom?: string,
  leftOrRight?: string,
  round?: string,
  zI?: string,
  shadow?: string,
  fCenter?: string,
  size?: string,
  font?: string,
  spacing?: string,
  gap?: string,
  
}